### ISSUE TITLE
Setting initial conditions, boundary values, free energy expression etc. for simulations from command line

### ISSUE THREAD

**Issue by lucasmyers97** [lucasmyers97/maier-saupe-lc-hydrodynamics#4]
# Problem
* `IsoSteadyState` (the only simulation thus far) relaxes the liquid crystal system into its lowest energy state
* It requires a boundary condition (here Dirichlet -- should extend to Neumann later) which affects the final state of the system
  - So far there are +1/2, -1/2, and uniform boundary conditions available
  - These are in the form of deal.II functions (an abstract function class) so that the particular functions (e.g. UniformConfiguration) inherit the necessary methods to set boundary conditions.
* The problem is that, as it currently stands, one must hardcode the particular boundary condition class into the simulation class.
* This is a pain, firstly because one has to change the code in several places to change the boundary condition.
* This is true also for the initial conditions (again, deal.II function classes), as well as the particular weak form free energy equations (these populate the finite element matrix, and could presumably be switched out at runtime to accommodate hydrodynamics, anisotropy, whatever).

# Goals (probably in order)
* Figure out a way to specify *upfront* what the particular boundary value method should be for a particular simulation, and then use that for the rest of the simulation without conditionals.
  - Ideally this would happen in the constructor of the simulation class, and would be a runtime property (as opposed to a templated something -- I think the singular virtual function call would not be a huge deal if we calculate all the boundary values at once).
  - Additionally we should not have to call a conditional every time we want to evaluate the boundary values method.
  - One suggestion from Tom was to use a pure virtual function -- if I understand this correctly we would pass in an instance of a class which inherits the deal.II function class, and the simulation class would just call the function class methods as if they had a regular definition.
  - Need to check on the actual implementation of that, but I would like the particular boundary value class (e.g. PlusHalfDefect) to live in the simulation class as a variable.
* Collect classes which set boundary values and initial conditions in their own library
  - Might want to give these classes extra variables (e.g. a name) so that it's easier to name outputted data files, and keep track of parameters.
* Rewrite simulation executable to take in command-line arguments
* Write Python script which will call executable and appropriately fill in command-line arguments (might want to put parameters into a different file, or possibly hardcode them into the script which calls the executable).
* Find some way to save parameters passed into executable (probably via hdf5 so they can be packaged with the data itself).
* Create a class (or maybe methods?) which fill in the finite element matrix given some weak form of the equations of motion -- collect those in their own libraries as well.

**Comment by tomeichlersmith** [comment]
So, from what I can see, you use the boundary conditions in the `IsoSteadyState<>::set_boundary_values()` function and no where else. Its definition is

https://github.com/lucasmyers97/maier-saupe-lc-hydrodynamics/blob/e9851d2a22e73e249f0cc9efc029e8bf01cfd9b3/app/simulations/IsoSteadyState.cpp#L627-L639

So right now, you are using the `BoundaryValuesMinusHalf<dim>()` function to define the boundary values which is constructed in place and then passed on to a `dealii` internal function which (if I'm interpreting the variable names correctly) use the function to calculate the values around the edges of the FE mesh. The good news is that this function _only_ needs to change the type of the boundary value function in order to change how the boundary values are calculated. This means we can isolate the necessary changes to this function. However, I have several questions about the _design_ of this application before I can make good suggestions.
- Are you planning on changing `dim` regularly? If not, you should not be carrying it around your entire class.
- It seems like you have isolated all of the work of this simulation into a class `IsoSteadyState` and some helper classes (various boundary value functions). From a software design POV, it makes sense to move these classes to their own header files to stay organized. Specifically, the boundary value functions seem to be general enough that they could be shared with other simulations and therefore moving them to their own headers would be helpful (perhaps in a `BoundaryValueFunctions` library? :eyes:)
- Your `main` is really small. It looks like `IsoSteadyState::run` should just be deleted and its contents copied into `main`. This would also make configuration easier because the values coming from `Boost::program_options` (e.g. `max_iterations`) wouldn't have to be passed into another function. The only reason I can think of to have a `run` is if you are planning on calling it from multiple different `main` (which right now you won't because it is just in one file).

My suggestion about a `pure virtual` function is already satisfied by `dealii::Function`. Basically, your `set_boundary_values` would become something like
```cpp
template <D>
void set_boundary_values(dealii::Function<D> boundary_value_function) {
  std::map<types::global_dof_index, double> boundary_values;
  VectorTools::interpolate_boundary_values(dof_handler,
                       0,
                       boundary_value_function,
                       boundary_values);
  for (auto &boundary_value : boundary_values)
    current_solution(boundary_value.first) = boundary_value.second;

  hanging_node_constraints.distribute(current_solution);
}
```
And then later (in your `run` or `main`)...
```cpp
IsoSteadState<D> iso_steady_state;
// other confiugration
if (cli_input == "BoundaryValueMinusHalf") {
  iso_steady_state.set_boundary_values(BoundaryValueMinusHalf<D>());
} else if (cli_input == "BoundaryValuePlusHalf") {
  iso_steady_state.set_boundary_values(BoundaryValuePlusHalf<D>());
} // add other options here
// begin run
```

**Comment by lucasmyers97** [comment]
To your questions:
* `dim` is liable to change: at these beginning stages I'm trying to get things to work in 2D because it's easier to visualize and debug, but in the future I will want to move to 3D because that's where actual science can happen (sometimes more interesting defect structures, etc.)
* Yeah, I have that listed in one of my goals. In particular everything that can be modularized (boundary conditions, initial conditions, code for weak form of equations of motion, maybe domain structure at some point) ought to be put in its own library.
* Yes, that's how all the deal.II tutorial functions are set up. I think I need to look at some later tutorial programs to get a handle on everything, but I think the point is to set up all of the parameters in the main function, collect them into some "descriptor" struct or class, and then pass that into the "run" function. Or maybe pass it into the constructor of the actual "simulation" object (here `IsoSteadyState`). In any case, I'm willing to believe that that is a good design choice before I actually understand the rationale.

Comments on your solution:
* I do not like it, but that might be the best solution given the constraints of C++.
* Ideally, the particular `BoundaryValues` child class would actually be a variable of `IsoSteadyState` -- this could definitely be done with templates, but then everything would have to be known at compile-time (unless you could just precompile all possibilities and then choose the correct one at runtime?).
* As a result of the above, you have to _pass in_ the `BoundaryValues` object to the `set_boundary_values` function -- it seems like the simulation should know within itself what its boundary values ought to be set to.
* Finally, there's a conditional statement at the location where `set_boundary_values` is called -- this seems bad because then, whenever you add a possible `BoundaryValues` instantiation (say I want a +1 defect) you have to add it into the conditional scheme in _that particular function_, rather than at the top of the class definition or site of the constructor or whatever.

**Comment by tomeichlersmith** [comment]
There is a fancier solution that would avoid conditions. The terminology is that you have a "factory" create instances of classes that are derived from a common base. This factory needs to have classes registered with it in a specific way, but once you get that set up, then you can create specific objects by name. I have done this a lot in my work with ldmx, so I could get you started in that direction. Be forewarned, this "factory" method is quit advanced, but an online lecture that is similar to what I've done can be found [here](http://www.cs.sjsu.edu/~pearce/modules/lectures/oop/types/reflection/prototype.htm). This lecture also comments on why this approach is "dangerous" and one method for getting around the "dangers". On LDMX, we do a slightly different dynamic instantiation approach.

- [this post](https://www.codeproject.com/Articles/7797/Dynamic-Class-Factory) has a template factory class which might be helpful as well

**Comment by lucasmyers97** [comment]
This was actually fixed a really long time ago. The solution that I landed on was to hardcode in a `BoundaryValuesFactory` function which returns a `unique_ptr<BoundaryValues>` object which is polymorphic. Currently it takes a `std::map<std::string, boost::any>` object in its constructor. There are some problems with this model, so I'm going to create a new issue to deal with these.
